spring:
#  datasource:
#    driver-class-name: org.h2.Driver
#    username: root
#    password: test
#  sql:
#    init:
#      schema-locations: classpath:db/init.sql
#      data-locations: classpath:db/data.sql