spring:
  application: test
  # datasource 数据源配置内容，对应 DataSourceProperties 配置属性类
  datasource:
    ##type: com.wyt.HikariCP.demo.multi.MultiDsPoolManager
    url: jdbc:mysql://127.0.0.1:3306/test?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    # HikariCP 自定义配置，对应 HikariConfig 配置属性类
    hikari:
      minimum-idle: 20 # 池中维护的最小空闲连接数，默认为 10 个。
      maximum-pool-size: 20 # 池中最大连接数，包括闲置和使用中的连接，默认为 10 个。
      idle-timeout: 500000
      connection-timeout: 60000
      max-lifetime: 540000
mybatis-plus:
    configuration:
      # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  datasource:
#    driver-class-name: org.h2.Driver
#    username: root
#    password: test
#  sql:
#    init:
#      schema-locations: classpath:db/init.sql
#      data-locations: classpath:db/data.sql